// packages/dockview-angular/src/lib/dockview/angular-header-actions-renderer.ts
import {
    Type,
    Injector,
    EnvironmentInjector,
    ApplicationRef,
    ComponentRef,
    EmbeddedViewRef,
    TemplateRef,
    createComponent,
} from '@angular/core';
import {
    DockviewApi,
    DockviewCompositeDisposable,
    DockviewGroupLocation,
    DockviewGroupPanel,
    DockviewGroupPanelApi,
    IDockviewHeaderActionsProps,
    IDockviewPanel,
    IHeaderActionsRenderer,
} from 'dockview-core';

/**
 * Angular implementation of a header-actions renderer. Mirrors the React
 * `ReactHeaderActionsRendererPart`: dockview-core only provides `api`,
 * `containerApi`, and `group` at init time, so this renderer augments the
 * component instance with the rest of `IDockviewHeaderActionsProps`
 * (`panels`, `activePanel`, `isGroupActive`, `headerPosition`, `location`)
 * and subscribes to the relevant events to keep them up to date.
 */
export class AngularHeaderActionsRenderer implements IHeaderActionsRenderer {
    private readonly _element: HTMLElement;
    private componentRef: ComponentRef<unknown> | null = null;
    private viewRef: EmbeddedViewRef<unknown> | null = null;
    private readonly appRef: ApplicationRef;
    private subscriptions: DockviewCompositeDisposable | null = null;

    get element(): HTMLElement {
        return this._element;
    }

    constructor(
        private readonly component: Type<unknown> | TemplateRef<unknown>,
        private readonly group: DockviewGroupPanel,
        private readonly injector: Injector,
        private readonly environmentInjector?: EnvironmentInjector
    ) {
        this._element = document.createElement('div');
        this._element.className = 'dv-angular-part';
        this._element.style.height = '100%';
        this._element.style.width = '100%';
        this.appRef = injector.get(ApplicationRef);
    }

    init(parameters: {
        containerApi: DockviewApi;
        api: DockviewGroupPanelApi;
    }): void {
        if (this.component instanceof TemplateRef) {
            // TemplateRef-based header actions cannot receive @Input()s;
            // render the template once and leave it static.
            this.viewRef = this.component.createEmbeddedView({}, this.injector);
            this._element.appendChild(this.viewRef.rootNodes[0] as HTMLElement);
            this.appRef.attachView(this.viewRef);
            this.viewRef.markForCheck();
            return;
        }

        this.componentRef = createComponent(this.component, {
            environmentInjector:
                this.environmentInjector ||
                (this.injector as EnvironmentInjector),
            elementInjector: this.injector,
        });

        const initialProps: IDockviewHeaderActionsProps = {
            api: parameters.api,
            containerApi: parameters.containerApi,
            panels: this.group.model.panels,
            activePanel: this.group.model.activePanel,
            isGroupActive: this.group.api.isActive,
            group: this.group,
            headerPosition: this.group.model.headerPosition,
            location: parameters.api.location,
        };
        this.assign(initialProps);

        const hostView = this.componentRef.hostView as EmbeddedViewRef<unknown>;
        const rootNode = hostView.rootNodes[0] as HTMLElement;
        this._element.appendChild(rootNode);
        this.appRef.attachView(hostView);
        this.componentRef.changeDetectorRef.markForCheck();

        this.subscriptions = new DockviewCompositeDisposable(
            this.group.model.onDidAddPanel(() => {
                this.assign({ panels: this.group.model.panels });
            }),
            this.group.model.onDidRemovePanel(() => {
                this.assign({ panels: this.group.model.panels });
            }),
            this.group.model.onDidActivePanelChange(() => {
                this.assign({
                    activePanel: this.group.model.activePanel as
                        | IDockviewPanel
                        | undefined,
                });
            }),
            parameters.api.onDidActiveChange(() => {
                this.assign({ isGroupActive: this.group.api.isActive });
            }),
            parameters.api.onDidLocationChange((event) => {
                this.assign({
                    location: event.location as DockviewGroupLocation,
                });
            })
        );
    }

    dispose(): void {
        this.subscriptions?.dispose();
        this.subscriptions = null;
        if (this.componentRef) {
            this.appRef.detachView(this.componentRef.hostView);
            this.componentRef.destroy();
            this.componentRef = null;
        }
        if (this.viewRef) {
            this.appRef.detachView(this.viewRef);
            this.viewRef.destroy();
            this.viewRef = null;
        }
    }

    private assign(partial: Partial<IDockviewHeaderActionsProps>): void {
        if (!this.componentRef) {
            return;
        }
        const instance = this.componentRef.instance as Record<string, unknown>;
        for (const key of Object.keys(partial) as Array<
            keyof IDockviewHeaderActionsProps
        >) {
            instance[key] = partial[key];
        }
        this.componentRef.changeDetectorRef.markForCheck();
    }
}

// packages/dockview-react/src/dockview/headerActionsRenderer.ts
import React from 'react';
import { ReactPart, ReactPortalStore } from '../react';
import {
    DockviewCompositeDisposable,
    DockviewMutableDisposable,
    DockviewApi,
    DockviewGroupPanel,
    DockviewGroupPanelApi,
    DockviewGroupLocation,
    PanelUpdateEvent,
    IHeaderActionsRenderer,
    IDockviewHeaderActionsProps,
} from 'dockview';

export class ReactHeaderActionsRendererPart implements IHeaderActionsRenderer {
    private readonly mutableDisposable = new DockviewMutableDisposable();
    private readonly _element: HTMLElement;
    private _part?: ReactPart<IDockviewHeaderActionsProps>;

    get element(): HTMLElement {
        return this._element;
    }

    get part(): ReactPart<IDockviewHeaderActionsProps> | undefined {
        return this._part;
    }

    constructor(
        private readonly component: React.FunctionComponent<IDockviewHeaderActionsProps>,
        private readonly reactPortalStore: ReactPortalStore,
        private readonly _group: DockviewGroupPanel
    ) {
        this._element = document.createElement('div');
        this._element.className = 'dv-react-part';
        this._element.style.height = '100%';
        this._element.style.width = '100%';
    }

    init(parameters: {
        containerApi: DockviewApi;
        api: DockviewGroupPanelApi;
    }): void {
        this.mutableDisposable.value = new DockviewCompositeDisposable(
            this._group.model.onDidAddPanel(() => {
                this.updatePanels();
            }),
            this._group.model.onDidRemovePanel(() => {
                this.updatePanels();
            }),
            this._group.model.onDidActivePanelChange(() => {
                this.updateActivePanel();
            }),
            parameters.api.onDidActiveChange(() => {
                this.updateGroupActive();
            }),
            parameters.api.onDidLocationChange((event) => {
                this.updateLocation(event.location);
            })
        );

        this._part = new ReactPart<IDockviewHeaderActionsProps>(
            this.element,
            this.reactPortalStore,
            this.component,
            {
                api: parameters.api,
                containerApi: parameters.containerApi,
                panels: this._group.model.panels,
                activePanel: this._group.model.activePanel,
                isGroupActive: this._group.api.isActive,
                group: this._group,
                headerPosition: this._group.model.headerPosition,
                location: parameters.api.location,
            }
        );
    }

    dispose(): void {
        this.mutableDisposable.dispose();
        this._part?.dispose();
    }

    update(event: PanelUpdateEvent): void {
        this._part?.update(event.params);
    }

    private updatePanels(): void {
        this.update({ params: { panels: this._group.model.panels } });
    }

    private updateActivePanel(): void {
        this.update({
            params: {
                activePanel: this._group.model.activePanel,
            },
        });
    }

    private updateGroupActive(): void {
        this.update({
            params: {
                isGroupActive: this._group.api.isActive,
            },
        });
    }

    private updateLocation(location: DockviewGroupLocation): void {
        this.update({ params: { location } });
    }
}
